language: cpp
compiler: g++-6
env: COMPILER=g++-6
dist: trusty
sudo: required
cache:
  directories:
  - "/usr/local/bin/"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - libfreetype6-dev
    - libjpeg-dev
    - libx11-dev
    - libxrandr-dev
    - libxcb1-dev
    - libx11-xcb-dev
    - libxcb-randr0-dev
    - libxcb-image0-dev
    - libgl1-mesa-dev
    - libflac-dev
    - libogg-dev
    - libvorbis-dev
    - libvorbisenc2
    - libvorbisfile3
    - libopenal-dev
    - libpthread-stubs0-dev
    - libstdc++6
    - libc6
    - libgcc1
    - libglew-dev
    - libgpgme11-dev
    - libsndfile1-dev
    - libudev-dev
script:
- sudo apt-get purge cmake
- mkdir ~/temp
- cd ~/temp
- echo "(Step 1/5) Downloading latest CMake.." && wget https://cmake.org/files/v3.8/cmake-3.8.2.tar.gz
- echo "(Step 2/5) Extracting CMake.." &&tar xzvf cmake-3.8.2.tar.gz > cmake-extractlog
- cd cmake-3.8.2/
- echo "(Step 3/5) Bootstrapping CMake.." && ./bootstrap > bootstrap-log
- echo "(Step 4/5) Make CMake.." && make -j4 > makelog
- echo "(Step 5/5) Install CMake.." && sudo make install > makelog-install
- which cmake
- cd ~/temp
- echo "Installing SFML..."
- pwd
- ls
- wget https://www.sfml-dev.org/files/SFML-2.4.2-sources.zip
- unzip SFML-2.4.2-sources.zip > sfml-downloadlog
- pwd
- ls
- cd SFML-2.4.2/src/SFML/Graphics
- rm CMakeLists.txt
- wget https://raw.githubusercontent.com/Sygmei/ObEngine/master/extlibs/build/SFML/Graphics/CMakeLists.txt
- cd ../../../
- mkdir build/
- cd build
- /usr/local/bin/cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=TRUE
  .. > install.log
- make >> install.log
- sudo make install >> install.log
- sudo ldconfig
- cd /home/travis/build/Sygmei/ObEngine
- sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
- sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
- export CC=/usr/bin/gcc-6
- export CXX=/usr/bin/g++-6
- gcc -v && g++ -v && /usr/local/bin/cmake --version
- mkdir build
- cd build
- "/usr/local/bin/cmake -DBUILD_TESTS=ON .."
- make -j6
- mv tests/ObEngineTests Tests
- "./Tests"
before_deploy:
- ls
- ls ../
- mv ../engine release
- mv src/Dev/ObEngineDev release/ObEngineDev
- mv src/Player/ObEnginePlayer release/ObEnginePlayer
- tar -zcvf obengine-linux.tar.gz release
- cd ..
- mv build/obengine-linux.tar.gz obengine-linux.tar.gz
- ls
deploy:
  provider: releases
  api_key:
    secure: JFo1WYUKFqG1a7mImIq0g5Sr4SDGFM0EmFP6FzrPjvhqA9pJp2MqH7ToPTVDDf5wZ2Bp0bVD+iKGvKJGPZ1lgIN2852qB8vGIU7MLGRTGxOytBM9sMMgo/Upy27Q6IpU/lYqXmdWO7BcLxsxFBLxY12ZrgYPLJYm6/uVVsZPxcTD8e3t+SD6MACiAb1XiTh0fA7DaiPZSRNJ77WBo+4YVFUkZn2QDsD3E0ZWpQap6NyV4f3FffmQCVKvhoK94+r1ig/RChdWimObO/vDBRVkchzi683F0BPJHxzB+8eVfRHKfM1GkB7WrG/AJ1VEASaBVF4d8LON1hobm3bFIhi5mhBK7zaK3thtsvXnkSYo9cHwYIg4S8btCiP/50EhBih69H+4FneiR1oLd0foolf9LPB3iKQ74/T7U9cRBveCOtwwrOX2eLrnB1NGJRxyuyKLB9BYHXNPZSvn2SQfK+aFhz042XTrMahNFps3H/PqvH6QJkQ2JZ+ZzlvCiNGygVzKgODodQ2t0oe7tS/1TXR/yF7dQVzFqvNGyuUsbDabz6mSHWe2Pe4tQgtGkdgf4SwwomDpldBvTvGEoNvdb/FvdFMi/gD/4MuYmzsb64cpelA3IWY8KM06wb9dUoDfs/L4ZmS4Wl/1ji+o9KDFd2pwZaKyCIwlPTJrDeIXvGIAHsI=
  file: build/obengine-linux.tar.gz
  on:
    repo: Sygmei/ObEngine
